---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The purpose of my project is to let a user observationally look at PGA players strokes gained and performance. The first tab allows users to look at historically who has played well at a course and what kinds of golfers might play well at that course through strokes gained. The second tab then lets a user look closer at a player’s past performances at a given a tournament. Finally, the last tab lets a user compare two golfers career stats. When put all together, the goal is to be able to potentially identify who might play well at a tournament next time. The data comes from a website that analyses all sports and general statistics https://www.advancedsportsanalytics.com/pga-raw-data . The main variables are player, year, made_cut(whether or not they were in top ½ after second round), strokes, tournament_name, and strokes gained for: Putting, Chipping, Approach, Driving, Non_putting, and Total. Strokes gained is calculated as the number of strokes gained on the field in the given category per round. For example, a total strokes gained of 1.2 and Putting of .3 means that golfer shot 1.2 strokes better than the field and of those .3 came from putting. Negative values are shots lost to the field. 

In the Expressing Uncertainty and Variability section, we learned about how plots can hide important information. One such example is bar plots. When representing summary statistics, we lose the variability and can’t see any outliers. Within the project, we see an example of this on the first tab. In the first plot there is averages of strokes gained in each category so a bar plot would hide the underlying variability and therefor a boxplot is a better choice. However, in the second plot since it is just a count of the number of strokes so it is perfectly fine to use a lollipop chart. The same goes for bar plots on made cuts and made cut percentage. In addition to the plots, there are also tables so that a user can see all information available for each data point.

In the Introduction, we learned about what makes visualizations harder to process for the reader. Some of the important ones covered were color, axis settings, and over cluttering. The plots used in my project are all clean and don’t try to do too much. The box plot on the first page could have been a multiple lines chart but in practice it was too messy to interpret. This is in tune with the data-to-ink ratio guideline as well. With bar plots, it is easy to mislead the reader when starting the plot not at 0. As such all bar plots in my project start at 0. Finally for coloring, we learned about different coloring schemes and when to use them. For the plots in my project, they are all unordered categorical variables which should be colored so that they stand out from each other but don’t dominate. This can be seen in the box plot on page 1 which also is color-blind friendly. On the bar plot in page 2 I used green for made cuts and red for missed cuts to help the reader make a quicker connection. 
Lastly for the Ethics section, we learned about the dangers of excluding data and what makes data ethical. Throughout the project I made sure to separate my own biases and look for any biases in the data and made sure not to remove any data to intentionally sway a reader’s perception. Instead of a table, I was going to have a radar chart for comparing strokes gained among players but quickly realized their flaw. Radar charts can often be misleading since the ordering of the categories can change how viewers perceive them.
	
The biggest limitation to my project was the dataset. While the strokes gained statistics are great there are many more categorical variables that could have been helpful and learning more about what makes a specific golfer good or a specific course hard. Things like par 3,4,5 scoring or scoring when when defending a lead would have been more interesting to look at. Also, not all golfers have data for strokes gained so a lot of plots end up empty. If I were to continue with this project, I would try to scrape the data from the PGA website so that I could implement more meaningful plots. With the extra stats I think I could even add a model that could give the user 10 golfers who it thinks might win. That way users who are not familiar with golf at least get some output outside of their own observations.
