---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
library(readxl)
library(readxl)
data <- read.csv("PGA_17_22.csv")
newdata <- data[c(1:5,12:14,21,25:27,29,31:37)]
newdata$play_yr <- paste(newdata$player, newdata$season)
```

```{r}
masters <- newdata %>% filter(tournament.name == "Valspar Championship") %>%
  filter(pos == 1)

tidy_tourny <-masters %>%
  pivot_longer(c(15:20), names_to = "Stat_cat", values_to = "response") 

  ggplot(data = tidy_tourny, aes(y = response, x = Stat_cat)) +
  geom_boxplot() +
  #facet_wrap(vars(player))+
  labs(x = "Strokes gained Catagory", y = "Strokes Gained on the Field")

```


```{r}
player_year <- newdata %>% mutate(plyr_yr = as.character(player) + as.character(season))
```

## user selects tournament and sees avg box plot of past winners in each catagpry
```{r}
library(shiny)

ui <- fluidPage(
        fluidRow(
          column(6,
            sidebarLayout(
              sidebarPanel(
                selectizeInput(inputId ="Tournychoice",
                               label = "Choose a Tournament",
                               choices = levels(
                                  factor(newdata$tournament.name)),
                               selected = ("Valspar Championship"))),
              selectizeInput(inputId ="Playerchoice",
                               label = "Choose a Player",
                               choices = levels(
                                  factor(newdata$player)),
                               selected = ("Scottie Scheffler"))),
                  mainPanel(plotOutput(outputId = "majorplot"))))),
        tabsetPanel(
        id = "tabset",
        tabPanel("panel 1", "one"),
        tabPanel("panel 2", "two")
      ),
        fluidRow(
          column(8,
            plotOutput(outputId = "minorplot"))
  
)
)


server <- function(input, output, session) {
  
  output$panel <- renderText({
    paste("Current panel: ", input$tabset)
  })
  
  df_update <- reactive({
    
    df_stat <- newdata %>% filter(tournament.name == input$Tournychoice) 
    
    df_win <- df_stat %>% filter(pos == 1)%>%
      pivot_longer(c(15:20), 
                   names_to = "Stat_cat", values_to = "response") %>%
      mutate(play_yr = fct_reorder(play_yr, desc(strokes))) 

  })
  
  
  output$majorplot <- renderPlot({
    
    ggplot(data = df_update(), aes(x = Stat_cat, y = response)) +
      geom_boxplot() +
      labs(x = "Strokes gained Catagory", 
           y = "Strokes Gained on the Field")
  })
  
  output$minorplot <- renderPlot({
    
    ggplot(data = df_update(), aes(x = play_yr, y = strokes))+
      geom_point() + 
      geom_segment( aes(x= play_yr, xend= play_yr, y=0, yend=strokes))+
      coord_flip()+
      geom_text(aes(label = strokes), vjust = 1.5, colour = "black")+
      ylim(0,288)
    
    
  })
  
  df_update2 <- reactive({
    df_scotty <- newdata %>% filter(player == "Scottie Scheffler")%>% mutate(made_cut = if_else(made_cut == 1,
                          true = "Made cut",
                          false = "Missed cut"))

Scotty_WM <- Scotty %>% filter(tournament.name == "Waste Management Phoenix Open")%>%group_by(made_cut)%>%summarise(ncut_made = n())
  })
  
  
  output$cut_plot <- renderPlot({
    
    ggplot(Scotty_WM, 
           aes(x = made_cut, y = ncut_made, fill = made_cut)) +
  geom_col()+
  scale_fill_manual(values = c("Made cut" = "green", "Missed cut" = "red"))
  })
  
  
}

shinyApp(ui, server)

```




```{r}
masters <- masters %>% mutate(player = fct_reorder(player, desc(strokes)))

ggplot(data = masters, aes(x = player, y = strokes))+
  geom_point() + 
  geom_segment( aes(x= player, xend= player, y=0, yend=strokes))+
  coord_flip()+
  geom_text(aes(label = strokes), vjust = 1.5, colour = "black")+
  ylim(0,288)

```

## graph of last 6 winners score 


```{r}
library(tidyverse)
library(viridis)
library(patchwork)
library(hrbrthemes)
library(fmsb)
library(colormap)

data_compare <- newdata[c(9,15:20)]
data_compare <- data_compare %>% filter(player == "Jon Rahm" | player == "Jordan Spieth")

  summarise(avg_putt = sum(sg_putt))
JJ <- data_compare %>% group_by(player) %>%



colors_border=c( rgb(0.2,0.5,0.5,0.9), rgb(0.8,0.2,0.5,0.9)  )
colors_in=c( rgb(0.2,0.5,0.5,0.4), rgb(0.8,0.2,0.5,0.4)  )

# Custom the radarChart !
radarchart( data_compare, axistype=1, 

  #custom polygon
  pcol=colors_border , pfcol=colors_in , plwd=4, plty=1 , 

  #custom the grid
  cglcol="grey", cglty=1, axislabcol="grey", caxislabels=seq(0,20,5), cglwd=1.1,

  #custom labels
  vlcex=0.8 
  )

# Legend
legend(x=0.85, y=1, legend = c("Golfer1", "Golfer2"), bty = "n", pch=20 , col=colors_border , text.col = "black", cex=0.9, pt.cex=1.6)
```
due to missing data ?

```{r}
library(hrbrthemes)
library(GGally)
library(viridis)

# Data set is provided by R natively
iris_data<- iris

Valspar <- newdata %>% filter(tournament.name == "Valspar Championship")

Valspar <- Valspar %>% mutate(pos = replace(pos,is.na(pos),100))
 
Valspar <- Valspar %>% group_by(player)%>% 
   mutate(haswon = if_else(min(pos) == 1, 
                          true = "yes",
                          false = "no"))

Valspar_HW <- Valspar %>% filter(haswon == "yes")%>% mutate(player = fct_reorder(player, desc(strokes)))

  





# Plot
ggparcoord(Valspar_HW,
    columns = 15:20, groupColumn = 9, order = "anyClass",
    #scale="uniminmax",
    showPoints = TRUE, 
    #splineFactor = TRUE,
    boxplot = TRUE,
    title = "Parallel Coordinate Plot for Past Winners"
    ) + 
  scale_color_viridis(discrete=TRUE) +
  theme_ipsum()+
  theme(
    plot.title = element_text(size=10)
  )

```


REPREX
```{r}
library(tidyverse)

test_df2 <- tibble(player = c("Caleb", "Caleb", "Caleb","Jeff","Bob"),
                   standings = c(1, 10, 7, 5, 1))
test_df2 

test_df2 %>% group_by(player) %>%
  mutate(haswon = if_else(min(standings) == 1,
                          true = "yes",
                          false = "no"))



test_want <-tibble(player = c("Caleb", "Caleb", "Caleb","Jeff","Bob"),
                   standings = c(1, 10, 7, 5, 1),
                   haswon = c("yes","yes","yes","no","yes"))
test_want
```

```{r}
Scotty <- newdata %>% filter(player == "Scottie Scheffler")%>% mutate(made_cut = if_else(made_cut == 1,
                          true = "Made cut",
                          false = "Missed cut"))




Scotty_WM <- Scotty %>% filter(tournament.name == "Waste Management Phoenix Open")%>%group_by(made_cut)%>%summarise(ncut_made = n())

ggplot(data = Scotty_WM, aes(x= made_cut)) + 
  geom_bar(stat = "identity")
  #scale_fill_manual(ncut_made = c("green", "red") )
  
 ggplot(Scotty_WM, aes(x = made_cut, y = ncut_made, fill = made_cut)) +
  geom_col()+
  scale_fill_manual(values = c("Made cut" = "green", "Missed cut" = "red"))


```


```{r}
library(shiny)

ui <- fluidPage(
        fluidRow(
          column(6,
            sidebarLayout(
              sidebarPanel(
                selectizeInput(inputId ="Tournychoice",
                               label = "Choose a Tournament",
                               choices = levels(
                                  factor(newdata$tournament.name)),
                               selected = ("Valspar Championship"))),
                  mainPanel(plotOutput(outputId = "majorplot"))))),
        fluidRow(
          column(8,
            plotOutput(outputId = "minorplot"))
  
)
)


server <- function(input, output, session) {
  
  output$panel <- renderText({
    paste("Current panel: ", input$tabset)
  })
  
  df_update <- reactive({
    
    df_stat <- newdata %>% filter(tournament.name == input$Tournychoice) 
    
    df_win <- df_stat %>% filter(pos == 1)%>%
      pivot_longer(c(15:20), 
                   names_to = "Stat_cat", values_to = "response") %>%
      mutate(play_yr = fct_reorder(play_yr, desc(strokes))) 

  })
  
  
  output$majorplot <- renderPlot({
    
    ggplot(data = df_update(), aes(x = Stat_cat, y = response)) +
      geom_boxplot() +
      labs(x = "Strokes gained Catagory", 
           y = "Strokes Gained on the Field")
  })
  
  output$minorplot <- renderPlot({
    
    ggplot(data = df_update(), aes(x = play_yr, y = strokes))+
      geom_point() + 
      geom_segment( aes(x= play_yr, xend= play_yr, y=0, yend=strokes))+
      coord_flip()+
      geom_text(aes(label = strokes), vjust = 1.5, colour = "black")+
      ylim(0,288)
    
    
  })
  
}

shinyApp(ui, server)
```

```{r}
ui <- fluidPage(
            sidebarLayout(
              sidebarPanel(
                selectizeInput(inputId ="Playerchoice",
                               label = "Choose a Player",
                               choices = levels(
                                  factor(newdata$player)),
                               selected = ("Scottie Scheffler")),
                selectizeInput(inputId = "Tournament",
                               label = "Choose a Tournament",
                               choices = levels(
                                 factor(newdata$tournament.name)),
                               selected = ("Valspar Championship"))),
              mainPanel(plotOutput(outputId = "majorplot"))))
        


server <- function(input, output, session) {
  
  df_update2 <- reactive({
    
    Scotty <- newdata %>% filter(player == input$Playerchoice) %>%                mutate(made_cut = if_else(made_cut == 1,
                          true = "Made cut",
                          false = "Missed cut"))
    
    Scotty <- Scotty %>%group_by(made_cut)%>%summarise(ncut_made = n())

  Scotty_WM <- Scotty %>% 
  filter(tournament.name == input$Tournament)%>%   group_by(made_cut)%>%summarise(ncut_made = n())
    
  })
  
  
  output$majorplot <- renderPlot({
    ggplot(df_update2(), aes(x = made_cut, y = ncut_made, fill = made_cut)) +
  geom_col()+
  scale_fill_manual(values = c("Made cut" = "green", "Missed cut" = "red"))
    
  })
  
  
}

shinyApp(ui, server)
```

